//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MariaPrintTray.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MariaPrintTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The program create by @marbocub is licensed by GPLv3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutherCredit {
            get {
                return ResourceManager.GetString("AutherCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Icon made by Freepik from www.flaticon.com is licensed by CC 3.0 BY. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IconCredit {
            get {
                return ResourceManager.GetString("IconCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTextAbout {
            get {
                return ResourceManager.GetString("MenuTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTextExit {
            get {
                return ResourceManager.GetString("MenuTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HKEY_LOCAL_MACHINE\SOFTWARE\Marbocub\MariaPrintSystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegKeyMariaPrintSystem {
            get {
                return ResourceManager.GetString("RegKeyMariaPrintSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Monitors\MariaPrintMon\Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegKeyPortMonitorSettings {
            get {
                return ResourceManager.GetString("RegKeyPortMonitorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OutputDirectory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegValueDirectory {
            get {
                return ResourceManager.GetString("RegValueDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PsShell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegValuePsShell {
            get {
                return ResourceManager.GetString("RegValuePsShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maria Print Management System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
